### ISSUE TITLE
Unable to use Testnet

### ISSUE THREAD

**Issue by Ataye** [TxnLab/use-wallet#109]
Following the steps in the readme, i've added wallet providers to app:

```
  const providers = useInitializeProviders({
    providers: [
      { id: PROVIDER_ID.DEFLY, clientStatic: DeflyWalletConnect },
      { id: PROVIDER_ID.PERA, clientStatic: PeraWalletConnect },
      { id: PROVIDER_ID.DAFFI, clientStatic: DaffiWalletConnect },
      { id: PROVIDER_ID.EXODUS }
    ],
    nodeConfig: {
      network: 'testnet',
      nodeServer: 'https://testnet-api.algonode.cloud/',
      nodeToken: '',
      nodePort: '443'
    }
  })
...
  return (
    <WalletProvider value={providers}>
      <RouterProvider router={router} />
    </WalletProvider>
  )
```
Then, on a page i have:

```
import { useWallet,
  DEFAULT_NODE_BASEURL,
  DEFAULT_NODE_TOKEN,
  DEFAULT_NODE_PORT } from '@txnlab/use-wallet'
const algodClient = new algosdk.Algodv2(DEFAULT_NODE_TOKEN, DEFAULT_NODE_BASEURL, DEFAULT_NODE_PORT)
...
const { activeAccount, activeAddress, signTransactions, sendTransactions } = useWallet()

const suggestedParams = await algodClient.getTransactionParams().do();
const ptxn = algosdk.makePaymentTxnWithSuggestedParamsFromObject({
        from: activeAddress,
        suggestedParams,
        to: constants.receiveWallet,
        amount: algosdk.algosToMicroalgos(total/algoInUsd/1000),
        note: new Uint8Array(Buffer.from(noteKey)),
      });
try {
      const encodedTransaction = algosdk.encodeUnsignedTransaction(ptxn)
      const signedTransactions = await signTransactions([encodedTransaction])
      const waitRoundsToConfirm = 4
      const { id } = await sendTransactions(signedTransactions, waitRoundsToConfirm)

      console.log('Successfully sent transaction. Transaction ID: ', id)
} catch (error) {
      console.log("Couldn't sign txn", error);
}
```
Testing with Pera connected using Pera Web, and when signing that tx i'm sent to Pera which shows `TESTNET` since i have the node set to testnet, i get:
```
Network mismatch
Your wallet is connected to a different network to this dApp. Update your wallet to the correct network (MainNet or TestNet) to continue.
```
Is there something i'm missing or overlooked?  I have connected to Pera using essentially the demo code (with ui formatting), with testnet set, and restarted the app a few times but i cannot gewt it to connect to testnet.

Any help is much appreciated.

**Comment by Ataye** [comment]
More Info:

Your readme under 'Signing and Sending Transactions' states:
```
import {
  useWallet,
  DEFAULT_NODE_BASEURL,
  DEFAULT_NODE_TOKEN,
  DEFAULT_NODE_PORT
} from '@txnlab/use-wallet'

const algodClient = new algosdk.Algodv2(DEFAULT_NODE_TOKEN, DEFAULT_NODE_BASEURL, DEFAULT_NODE_PORT)
```
for signing txns, but those DEFAULT* comes from `[index.ts] export * from './constants'` which are the hard coded defaults, which default to mainnet!!!  If you want to use the network details from `nodeConfig` i.e. TESTNET, then you need to do something like:
```
  const algodClient = clients?.[activeAccount?.providerId]?.algodClient || null
```
to get a pre-initialised algod client loaded with the nodeConfig values.  Otherwise you get the default mainnet values!

Might be a good idea to complete the `Node configuration` section by stating that in order to use the values from nodeConfig, you need to grab the pre-loaded algod client from the provider in use, rather than the earlier example of using new algosdk.Algodv2() with the DEFAULT*s from `@txnlab/use-wallet`?

**Comment by drichar** [comment]
A simpler approach would be to define your own constants for `NODE_TOKEN`, `NODE_BASEURL`, and `NODE_PORT` and pass them to both `nodeConfig` and your app's algod client instance:

```tsx
import algosdk from 'algosdk'
import {
  NODE_BASEURL,
  NODE_TOKEN,
  NODE_PORT
} from '@/constants'

const algodClient = new algosdk.Algodv2(NODE_TOKEN, NODE_BASEURL, NODE_PORT)

const providers = useInitializeProviders({
  providers: [...],
  nodeConfig: {
    network: 'testnet',
    nodeServer: NODE_BASEURL,
    nodeToken: NODE_TOKEN,
    nodePort: NODE_PORT
  }
  algosdkStatic: algosdk
})
```

**Comment by Ataye** [comment]
Yes that is another option.  See i'm new to the project, and when integrating it as per the readme, i'm led to believe that setting `nodeConfig` will also set the network for the `Signing and Sending Transactions` section which i previously implemented.

Some kind of note in the readme docs would have helped me to understand this, and thus implement either of our suggestions.

**Comment by drichar** [comment]
I can see how the transaction example code could be confusing.

In the code examples prior to the transaction example, `nodeConfig` is not set and the default configuration is used. In that scenario, the library's `DEFAULT_*` variables can be used to instantiate your app's algod client. But that's not a very good way to demonstrate using the library, and there's no explanation about why that works.

The recommended approach would be the example I provided above: passing the same variables to your algod client instance and the `nodeConfig`. They should match. I'll update the README and transaction example code.

Thank you @Ataye, really appreciate your feedback!

**Comment by Ataye** [comment]
No worries.  I was planning to put together something similar to this project ala Rainbowkit etc, but you have already done the hard work so appreciate it and happy to support :)

Also, just FYI, Exodus doesn't support testnet it seems!
