### ISSUE TITLE
Ability to specify custom signer in signTransactions

### ISSUE THREAD

**Issue by aorumbayev** [TxnLab/use-wallet#120]
There are cases when there is a need to perform rekeying back to original addresses, in such cases signer is the current address to which it was rekeyed. However txn fields such as sender, receiver and rekeyTo are all set to original address. 

Defly and Pera have an ability to pass authAddress to SignersAccount on their respective signTransactions function. In use-wallet though behaviour is rather implicit and varies depending on wallet provider. 

Would be great to have an ability to select which txns in txn group has to be signed by a different signer and cover that in documentation.

**Comment by drichar** [comment]
Rekeyed signing is currently supported by all of the wallet providers... _except_ kmd. From talking with you on Discord about this, I know that's where you were running into issues.

The kmd client iterates over each transaction and checks whether the Sender is a connected address, and if so, passes it to the `algosdk.Kmd.signTransaction` method for signing.

It should also be checking the ReKeyTo field and using `algosdk.Kmd.signTransactionWithSpecificPublicKey` for rekeyed signing. I'll make sure this gets added.
