### ISSUE TITLE
Cannot parse class method with private name.

### ISSUE THREAD

**Issue by g-anwuli** [TxnLab/use-wallet#131]
I can't seem to use useWallet in safari browser, it only works in latest version of safari. i keep getting these errors "SyntaxError: Unexpected private name #composeTransactions. Cannot parse class method with private name."

I would love an alternative approach or solution to this issue thanks.

**Comment by drichar** [comment]
Need to take a look at the [target environment](https://tsup.egoist.dev/#target-environment) in the v3's build config to see what targeting older versions of Safari (before private method support) does to the output bundle.

**Comment by drichar** [comment]
Closing this but please let me know if you still have issues in older versions of Safari with https://github.com/TxnLab/use-wallet/releases/tag/v3.0.0
