### ISSUE TITLE
multiple non-consecutive signers issue

### ISSUE THREAD

**Issue by ctubio** [TxnLab/use-wallet#132]
🎁 hiii

i do believe the following function works nice for groups with a single signer or with multiple consecutive, liike:
- txn0: signerA

or

- utxn0: signerA
- stxn1: signerB
- stxn2: signerB

is returned as-is

but in case of non-consecutive, it returns duplicated txns and while duplicating misses the txn on each replaced index, liike:

- utxn0: signerA
- stxn1: signerB
- utxn2: signerA

is returned as:

- utxn0: signerA
- stxn1: signerB
- stxn1: signerB

(note utxn2 is lost and replaced by a duplicated stxn1)

(note² in the examples, signerA will sign a txn, and signerB already signed it so will not sign nothing on this request)

https://github.com/TxnLab/use-wallet/blob/380bd15722ebf5f12b06815f9633df4be7897d90/src/clients/pera/client.ts#L204-L213

thank you for your awesome work'¡

**Comment by drichar** [comment]
This should be fixed in v3, where the `returnGroup` logic is removed and `signTransactions` simply returns `stxn[i]` (with `i` matching its index in `txnGroup`) or null if unsigned.

**Comment by ctubio** [comment]
![aee4b7856cdf28a89a3bcf3308a72c47](https://github.com/TxnLab/use-wallet/assets/1634027/444492c4-d6ff-490d-ac8b-5b905d1a4de6)
