### ISSUE TITLE
Defly not working anymore

### ISSUE THREAD

**Issue by zackmorgs** [TxnLab/use-wallet#149]
The code I used that had setup for connecting Defly wallet previously worked, but suddenly it's not executing the correct behavior. I cannot connect my app to a Defly wallet anymore. 

Let me know if there are any fixes in the works.

**Comment by zackmorgs** [comment]
After testing this out on my mac, defly is working there. (using chrome not safari)

**Comment by drichar** [comment]
Can you describe the issue you're experiencing w/ Defly? Is there an error message? Also please provide more info about your environment:

- Device/OS
- Browser/version
- Version of use-wallet installed in your app

A link your your project repo or a minimum reproducible example would also help with to isolate/debug the issue.

**Comment by drichar** [comment]
Closing this, but will reopen if you can provide more details and/or a reproducible example
