### ISSUE TITLE
[v3] Pera needs global shim

### ISSUE THREAD

**Issue by PhearZero** [TxnLab/use-wallet#191]
# Overview

v3 with pera fails to connect with message 

```
ReferenceError: global is not defined
```

# Resolution

Add shim to `index.html` but it may be better to update the pera library

```html
<head>
  <script>
        // Suggest that Pera to use globalThis instead of global | window
        globalThis.global = globalThis
  </script>
</head>
```

# Details

-  @txnlab/use-wallet-react 3.0.0-rc.2
-  Vite React-TS project

**Comment by drichar** [comment]
Yeah this is an issue I get a lot in the use-wallet channel on NFD's Discord, and there's an open issue for it on Pera Connect: https://github.com/perawallet/connect/issues/101

The Vite example apps for v3 all include the index.html shim: https://github.com/TxnLab/use-wallet/blob/v3/examples/react-ts/index.html#L12

It would be nice to have this resolved in Pera Connect v2, if possible. I don't think it qualifies as a use-wallet issue per se, other than drawing more attention to it in the documentation.

**Comment by PhearZero** [comment]
Fixed! Going to issue a PR to pera, could be useful while we migrate to `v2`

- https://github.com/awesome-algorand/walletconnect-socket-transport

```bash
npm install awesome-algorand/walletconnect-socket-transport --save
```
