### ISSUE TITLE
Integration for React Native

### ISSUE THREAD

**Issue by JupiterXiaoxiaoYu** [TxnLab/use-wallet#20]
The common issue for React Native projects to adapt React libraries is that some of the libraries have some other React dependencies and react-native doesn't have a corresponding peer.
For example, js Algo SDK has a dependency which I think is crypto and the react-native project cannot directly use the one provided for React.
Hope we can have a react native version (expo preferred)

**Comment by gabrielkuettel** [comment]
Yeah it appears that main issue with `use-wallet` would be supporting the polyfills that `algosdk` relies on. I can take a look at setting up an Expo project and seeing if there's a path forward there.

**Comment by drichar** [comment]
We're now using `algosdk` v2 and those polyfills are no longer required. Have you tried the latest version of use-wallet in your React Native project?

**Comment by drichar** [comment]
Pera Connect does not support React Native: https://github.com/perawallet/connect/issues/85

Neither does Defly or Daffi (as they're both forks of Pera's connect library).

WalletConnect does offer libraries specifically for React Native support in v2, but they aren't the same as the standard web packages we use for our WalletConnect provider. Their RN libraries aren't even stable yet... still in "release candidate" stage and being actively developed. https://docs.walletconnect.com/2.0/reactnative/walletconnectmodal/about#roadmap

I'll track the progress of WalletConnect's React Native support, but for now I'd say it isn't on our roadmap.
