### ISSUE TITLE
move the algod client to store

### ISSUE THREAD

**Issue by drichar** [TxnLab/use-wallet#213]
When switching networks, the algod client needs to be reactive in order to continue working on the new network. This is currently only working in the SolidJS adapter thanks to https://github.com/TxnLab/use-wallet/pull/204, which moved the client to the `@tanstack/solid-store` reactive store.

The same should be done in the core library and the other framework adapters.

**Comment by SilentRhetoric** [comment]
I want to add that the algodClient is currently reactive in the SolidJS adapter, but it is not being set when the app is first initialized. In order to get this working generically, the store will need to have its algodClient set from the active network when the app first mounts.

**Comment by drichar** [comment]
Closed by https://github.com/TxnLab/use-wallet/pull/224
