### ISSUE TITLE
algosdk is a CommonJS module

### ISSUE THREAD

**Issue by scholtz** [TxnLab/use-wallet#216]
After upgrade from v2 to v3 of the use-wallet I have started to receive error: ```SyntaxError: Named export 'Algodv2' not found. The requested module 'algosdk' is a CommonJS module, which may not support all module.exports as named exports.```

![image](https://github.com/user-attachments/assets/4dc9544f-0a8f-40b6-ac61-787039fd7ffe)

we are using the nextjs with typescript, i have checked that the algosdk is correctly installed (2.8.0), i have tried to downgrade it, i have tried to reinstall the node modules... 

the error originates in the use wallet lib.. for the record i can use ```import { Algodv2 } from "algosdk";``` in my project

![image](https://github.com/user-attachments/assets/4028002e-c504-44f2-93f6-3d7bcbc72413)

i have checked the example project here and dont see any typescript difference.. https://github.com/TxnLab/use-wallet/blob/main/examples/nextjs/tsconfig.json

anybody has faced the same issue before?

**Comment by TheGateKeeper1995** [comment]
I'm getting the same issue, but not on typescript, and with Next Js as well

**Comment by scholtz** [comment]
i fixed my issue by upgrading the nextjs and changing the filesystem structure

before it was not using the src folder, so i moved everything to src updated a lot of other configs (eg tailwind, typescript..) and it seems to work now

basically i moved from /pages/index.tsx to /src/app/page.tsx which fixed the issue

**Comment by SilentRhetoric** [comment]
I am encountering the same error in SolidStart. 

I believe that the issue can be resolved with a small change here:

https://github.com/TxnLab/use-wallet/blob/1dd8f538d77167382884074499a3c522fed78fa3/packages/use-wallet/src/store.ts#L1C1-L1C34

```diff
- import { Algodv2 } from 'algosdk'
+ import algosdk from 'algosdk'
+ const { Algodv2 } = algosdk 
```
