### ISSUE TITLE
how to setup 2 instances of useWallet on one page?

### ISSUE THREAD

**Issue by scholtz** [TxnLab/use-wallet#223]
My usecase is the bridge between AVM chains.

I want to have source chain wallet connected first so that person selects the source account address easily.

Then i want to have destination chain wallet connected if user controls the destination account and he is not yet opted in to the bridged asset.

Next after the review i need to initiate signTx to the source chain wallet.

i can iniciate two `WalletManager` instances, however there is no "store prefix" or something similar in the config.. Also on the page when i want to use the ```const { wallets, activeAccount } = useWallet();``` there is no parameter to be supplied in the useWallet method to select proper wallet manager instance

@drichar What do you suggest to do pls?

**Comment by drichar** [comment]
The framework adapters rely on the core library's `WalletManager` being a singleton. I don't see the benefit of modifying them all to satisfy a very narrow use case.

I would suggest building/forking your own adapter that is designed to work with multiple manager instances. The `useWallet` hook/function it exports could accept an argument to select the instance you want to access. All you would need is a `WalletManager` configuration option to set a custom local storage key.
