### ISSUE TITLE
Better error message explaining why Exodus and AlgoSigner are not available

### ISSUE THREAD

**Issue by stefek99** [TxnLab/use-wallet#25]
I was encountering these errors:
<img width="540" alt="image" src="https://user-images.githubusercontent.com/249703/208090303-9e62c024-03cc-4175-95d4-72693882b704.png">

Someone else posted on Discord:
<img width="809" alt="image" src="https://user-images.githubusercontent.com/249703/208090362-d98faf4b-268d-4ac8-8520-e288e917204a.png">

Source: https://discord.com/channels/925410112368156732/1039592016704721019/1051855605003984938

### Better error message

AlgoSigner: https://github.com/TxnLab/use-wallet/blob/71d6908d32712baa03e549eb9dde6b8e67db04bc/src/clients/algosigner/client.ts#L74

Exodus: https://github.com/TxnLab/use-wallet/blob/71d6908d32712baa03e549eb9dde6b8e67db04bc/src/clients/exodus/client.ts#L61

It's not really an error, someone does not have an extension installed, first thing that comes to mind:

`console.warn("AlgoSigner not initialised. Reason: no extension installed.")`

Something that would explain what is happening rather than sea of red in the console.

**Comment by gabrielkuettel** [comment]
I agree a warning is better. I'll patch this, thanks.

**Comment by robdmoore** [comment]
Even a warning is probably overkill? Side-note: it would be cool to detect when an extension isn't available so that you can optionally hide the provider, show an install link or some other thing.

**Comment by drichar** [comment]
> Even a warning is probably overkill? Side-note: it would be cool to detect when an extension isn't available so that you can optionally hide the provider, show an install link or some other thing.

I really like the idea of showing a link to the Chrome extension if it isn't installed, and hiding it altogether in an unsupported browser.

**Comment by gabrielkuettel** [comment]
Changed from an error to a warning, with a link to installed the extension in 1.1.6: https://github.com/TxnLab/use-wallet/releases/tag/v1.1.6

<img width="370" alt="Screen Shot 2023-01-16 at 16 28 36" src="https://user-images.githubusercontent.com/40471143/212774555-f3da88bd-1f45-4674-90f6-d9b836065fe7.png">
