### ISSUE TITLE
Add support for in-browser mnemonic accounts for UI e2e testing scenarios

### ISSUE THREAD

**Issue by aorumbayev** [TxnLab/use-wallet#26]
Just a suggestion for cases when it's not possible to fully e2e test things like perawallet or myalgo, a simple in-browser mnemonic account is useful for e2e tests in tools like cypress, selenium, playwright because it's easier to automate input of a mnemonic phrase rather than automation real providers.

Can function similar to the existing KMD provider - on select it asks for a passphrase of an account and that's it. Related documentation or warnings can be supplied that it's only recommended in testing/dev environments.

Let me know if more examples of how this provider can be useful for ui testing just let me know. Also if you'd agree that this is useful i can try the initial pr draft myself - i believe it should be relatively easy to implement.

**Comment by aorumbayev** [comment]
Added PR with proposal https://github.com/TxnLab/use-wallet/pull/28

**Comment by gabrielkuettel** [comment]
Huge thanks for that PR. Closing this issue as your PR is in review. :)
