### ISSUE TITLE
What is the reason for shouldShowSignTxnToast PeraWalletConnect false?

### ISSUE THREAD

**Issue by stefek99** [TxnLab/use-wallet#30]
Here it is set by default to `false`: https://github.com/TxnLab/use-wallet/blob/1bca5ab15d72076e5430b200f178ee76a7b8c7d9/src/clients/pera/client.ts#L63

Originally the default is set to `true`:

https://github.com/perawallet/connect#options

----

### Why asking?

Previously I had a single line of code and I was happy:

`const walletProviders = initializeProviders();`

Then I've realised that Pera doesn't trigger the popup and I need to manually initialise it.

**BUT**

> Passing an empty array as the first argument enables all of the default providers. 

Configuring Pera caused other wallets to disappear and as a consequence I need to add all other wallets manually.

```
import { PROVIDER_ID, pera, myalgo, kmd, algosigner, defly, exodus, walletconnect } from "@txnlab/use-wallet";

const walletProviders = {
  [PROVIDER_ID.PERA]: pera.init({
    clientOptions: {
      shouldShowSignTxnToast: true,
    }
  }),
  [PROVIDER_ID.MYALGO]: myalgo.init({}),
  [PROVIDER_ID.DEFLY]: defly.init({}),
  [PROVIDER_ID.KMD]: kmd.init({}),
  [PROVIDER_ID.ALGOSIGNER]: algosigner.init({}),
  [PROVIDER_ID.EXODUS]: exodus.init({}),
  [PROVIDER_ID.WALLETCONNECT]: walletconnect.init({})
};
```

_(passing empty `clientOptions` to use defaults)_

Ideally there should be an option to keep the defaults + configure individual wallet.

**Comment by drichar** [comment]
A simpler API for initialization might be to combine the `initializeProviders` "shortcut" method and the manual, mapped config:

```jsx
const walletProviders = initializeProviders([
  {
    id: PROVIDER_ID.PERA,
    clientOptions: {
      shouldShowSignTxnToast: true
    }
  },
  PROVIDER_ID.MYALGO,
  PROVIDER_ID.DEFLY,
  // etc
])
```

**Comment by drichar** [comment]
Also, I think it does make sense to start with client defaults. Even though we set `shouldShowSignTxnToast` to false in the NFD front end, making that the default for the library is bound to confuse people.

**Comment by gabrielkuettel** [comment]
Making it easier to configure the other providers when using custom configurations is in the pipeline. We'll keep this issue open and update here when we've made this change.
