### ISSUE TITLE
Allow specification of network by name

### ISSUE THREAD

**Issue by barnjamin** [TxnLab/use-wallet#4]
Allow `SupportedLedger` or string name for network during `connect` call to pass to the wallet
https://github.com/TxnLab/use-wallet/blob/main/src/clients/algosigner.ts#L93

**Comment by HIT2022** [comment]
If possible, moving the entire NODE_*-related config from env. vars and into the connect calls would be ideal. I'm using NEXT_PUBLIC_NODE_SERVER with another package for example.

**Comment by gabrielkuettel** [comment]
> If possible, moving the entire NODE_*-related config from env. vars and into the connect calls would be ideal. I'm using NEXT_PUBLIC_NODE_SERVER with another package for example.

In a future version we'll allow those to be set via a configuration file.

**Comment by gabrielkuettel** [comment]
Clients are not configured without using env variables as of V1. See https://github.com/TxnLab/use-wallet#provider-configuration
