### ISSUE TITLE
AlgoSigner needs additional property to sign with a rekeyed account

### ISSUE THREAD

**Issue by acfunk** [TxnLab/use-wallet#47]
`authAddr` is required for a rekeyed account. 

Here is their spec:
https://github.com/PureStake/algosigner/blob/develop/docs/dApp-integration.md#transaction-requirements

**Comment by pbennett** [comment]
It's kind of broken the way algosigner handles this.  Algosigner explicitly requires you to define the networks in it, upfront, yet then doesn't use those networks to query the node and determine if the account is rekeyed and sign with the other account.  Pera, Defly, MyAlgo all do this.  😞

**Comment by pbennett** [comment]
Generically though if algosigner needs this, use-wallet presumably has to allow the caller to provide this data (as the caller is responsible for networks, submitting the transaction, etc.).  The auth-addr is returned (optionally) in the accounts API from algod.
Ie:
https://developer.algorand.org/docs/rest-apis/algod/v2/#get-v2accountsaddress
call it like /v2/accounts/{ADDRESS}?exclude=all
as there's no reason to get assets, etc.  The auth-addr property will be present if the account has been rekeyed - it will be the account it was rekeyed to.
