### ISSUE TITLE
outdate packages.json

### ISSUE THREAD

**Issue by scholtz** [TxnLab/use-wallet#54]
I have tried to do ```npm install``` but it has failed with errors 

```
Could not resolve dependency:
npm ERR! peer algosdk@"^1.23.2" from @blockshake/defly-connect@1.0.0
```

Then i upgraded defly connect, and got
```
Could not resolve dependency:
npm ERR! peer algosdk@"^1.23.2" from @perawallet/connect@1.1.1
```
.. many other packages are not updated in the packages.json, so i did ```npm i --legacy-peer-deps`` but audit shows 

```
23 vulnerabilities (22 high, 1 critical)
```

i am not able to run ```npm update --save``` because of 

```
Could not resolve dependency:
npm ERR! peer rollup@"^2.28.2" from rollup-plugin-rename-node-modules@1.3.1
```

Then i did ```yarn install``` and it has passed, but ```yarn audit``` shows

```
Severity: 63 High | 14 Critical
```

**Comment by scholtz** [comment]
node --version : v18.14.1
npm --version : 9.3.1

**Comment by drichar** [comment]
@scholtz https://github.com/TxnLab/use-wallet/releases/tag/v1.2.10 should fix the dependency resolution errors you were seeing. Let me know if encounter any other issues installing w/ NPM.

The vulnerabilities reported in the audit are all related to Storybook (which can be used to preview components in local development). None of them affect use-wallet itself.

In a future version I may split the published library and the Storybook modules into separate packages in a monorepo.

**Comment by drichar** [comment]
Closing this, works for me using Node 18.14.2 / NPM 9.5.0
If you still have any issues @scholtz let me know
