### ISSUE TITLE
polyfill instruction link broken

### ISSUE THREAD

**Issue by iskysun96** [TxnLab/use-wallet#77]
⚠️ If you're using create-react-app and webpack 5 (most newer React projects), you will need to install polyfills. Follow [these directions](https://github.com/TxnLab/use-wallet#webpack-5).

This link is broken. Can you update the polyfills instruction?

**Comment by drichar** [comment]
The instructions were removed in https://github.com/TxnLab/use-wallet/pull/46 as the polyfills are no longer needed. Not removing the link to the instructions was an oversight. Sorry for the confusion! The link has been removed.
