### ISSUE TITLE
Using walletConnect to connect another blockchain(rainbowKit) while enabling walletConnect in use-Wallet cause error of `Failed to execute 'define' on 'CustomElementRegistry': the name "wcm-button" has already been used with this registry`

### ISSUE THREAD

**Issue by jingxuan98** [TxnLab/use-wallet#99]
I am using walletConnect to connect another blockchain via (rainbowKit with wallet-conenct option) while enabling walletConnect in use-Wallet for algorand as well,

This cause an error of `Failed to execute 'define' on 'CustomElementRegistry': the name "wcm-button" has already been used with this registry`, seems like its caused by the `@walletconnect/modal-sign-html` when initializing the wallet-connect registering something twice..
![Screenshot 2023-07-24 at 4 49 18 PM](https://github.com/TxnLab/use-wallet/assets/43902263/21cd41c1-3f3b-48fd-8284-95528ea6e5b5)

Any idea how can i solve this?

**Comment by drichar** [comment]
Can you provide some more details about your project? Either a link to the repo (if public) or a minimal reproducible example?

**Comment by drichar** [comment]
Closing this for now. If you can provide reproduction steps or an example I'll be happy to reopen.
